pipeline {
    agent any
    
    tools {
        nodejs "node"
    }
    
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/datalow-del/CICDPipe.git'
            }
        }
        
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Pwdwadwdwdroceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
        
        stage('Launch App') {
            steps {
                sh 'node app.js &'
            }
        }
    }
    
     post {
        failure {
            echo 'Pipeline failed. Notify the team for investigation.'
            // Add any additional steps to be taken on failure
        }

        success {
            echo 'Pipeline succeeded! Deploying to production...'
            // Add steps for deploying to production, if applicable
        }
    }
}
